name: Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    name: Run Unit Tests
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - name: Run tests
        run: python3 -m unittest
        
